/*
 * BuyForm.java
 * Created on __DATE__, __TIME__
 */

package com.amar.soccer.dinner;

/**
 *
 * @author  __USER__
 */
public class BuyForm extends javax.swing.JPanel
{

	/** Creates new form BuyForm */
	public BuyForm()
	{
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jLabel1 = new javax.swing.JLabel();

		jLabel1.setText( "buy" );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( this );
		this.setLayout( layout );
		layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup().addGap( 52 , 52 , 52 ).addComponent( jLabel1 ).addContainerGap( 327 , Short.MAX_VALUE ) ) );
		layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup().addGap( 63 , 63 , 63 ).addComponent( jLabel1 ).addContainerGap( 220 , Short.MAX_VALUE ) ) );
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}
