/*
 * LaunchForm.java
 * Created on __DATE__, __TIME__
 */

package com.amar.soccer.dinner;

/**
 *
 * @author  __USER__
 */
public class LaunchForm extends javax.swing.JPanel
{

	/** Creates new form LaunchForm */
	public LaunchForm()
	{
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jLabel1 = new javax.swing.JLabel();

		jLabel1.setText( "\u53d1\u8d77\u56e2\u8d2d" );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( this );
		this.setLayout( layout );
		layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup().addGap( 68 , 68 , 68 ).addComponent( jLabel1 ).addContainerGap( 284 , Short.MAX_VALUE ) ) );
		layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup().addGap( 84 , 84 , 84 ).addComponent( jLabel1 ).addContainerGap( 199 , Short.MAX_VALUE ) ) );
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}
