/*
 * RegistForm.java
 * Created on __DATE__, __TIME__
 */

package com.amar.soccer.user;

/**
 *
 * @author  __USER__
 */
public class RegistForm extends javax.swing.JPanel
{

	/** Creates new form RegistForm */
	public RegistForm()
	{
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jLabel1 = new javax.swing.JLabel();

		jLabel1.setText( "\u7528\u6237\u6ce8\u518c" );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( this );
		this.setLayout( layout );
		layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent( jLabel1 ).addContainerGap( 340 , Short.MAX_VALUE ) ) );
		layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup().addGap( 94 , 94 , 94 ).addComponent( jLabel1 ).addContainerGap( 189 , Short.MAX_VALUE ) ) );
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}
