/*
 * UserForm.java
 * Created on __DATE__, __TIME__
 */

package com.amar.soccer.user;

/**
 *
 * @author  __USER__
 */
public class UserForm extends javax.swing.JPanel
{

	/** Creates new form UserForm */
	public UserForm()
	{
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jLabel1 = new javax.swing.JLabel();

		jLabel1.setText( "\u7528\u6237\u4fe1\u606f" );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( this );
		this.setLayout( layout );
		layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup( javax.swing.GroupLayout.Alignment.TRAILING ,
				layout.createSequentialGroup().addContainerGap( 292 , Short.MAX_VALUE ).addComponent( jLabel1 ).addGap( 60 , 60 , 60 ) ) );
		layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup().addGap( 70 , 70 , 70 ).addComponent( jLabel1 ).addContainerGap( 213 , Short.MAX_VALUE ) ) );
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}
