/*
 * SettingForm.java
 * Created on __DATE__, __TIME__
 */

package com.amar.soccer.setting;

import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class SettingForm extends javax.swing.JPanel
{
	ReadWriteSetting readWriteSetting = null;
	SettingModel settingModel = null;
	/** Creates new form SettingForm */
	public SettingForm()
	{
		initComponents();

		readWriteSetting = new ReadWriteSetting();
		settingModel = readWriteSetting.getSetting();
		ServerIpTextField.setText( settingModel.getServerIp() );
		ServerPortTextField.setText( settingModel.getServerPort() + "" );
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		ServerPortTextField = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		SaveButton = new javax.swing.JButton();
		ServerIpTextField = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();

		jLabel1.setText( "ServerIp\uff1a" );

		jLabel2.setText( "ServerPort\uff1a" );

		SaveButton.setText( "\u4fdd\u5b58" );
		SaveButton.addMouseListener( new java.awt.event.MouseAdapter()
		{
			public void mouseReleased( java.awt.event.MouseEvent evt )
			{
				SaveButtonMouseReleased( evt );
			}
		} );

		jButton2.setText( "\u6062\u590d" );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( this );
		this.setLayout( layout );
		layout.setHorizontalGroup( layout
				.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
				.addGroup(
						layout.createSequentialGroup().addContainerGap( javax.swing.GroupLayout.DEFAULT_SIZE , Short.MAX_VALUE ).addComponent( jLabel1 ).addGap( 18 , 18 , 18 )
								.addComponent( ServerIpTextField , javax.swing.GroupLayout.PREFERRED_SIZE , 187 , javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 40 , 40 , 40 )
								.addComponent( jLabel2 ).addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED )
								.addComponent( ServerPortTextField , javax.swing.GroupLayout.PREFERRED_SIZE , 62 , javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 124 , 124 , 124 ) )
				.addGroup( layout.createSequentialGroup().addGap( 149 , 149 , 149 ).addComponent( jButton2 ).addGap( 59 , 59 , 59 ).addComponent( SaveButton ).addContainerGap( 267 , Short.MAX_VALUE ) ) );
		layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel1 )
										.addComponent( ServerIpTextField , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE )
										.addComponent( jLabel2 )
										.addComponent( ServerPortTextField , javax.swing.GroupLayout.PREFERRED_SIZE , javax.swing.GroupLayout.DEFAULT_SIZE , javax.swing.GroupLayout.PREFERRED_SIZE ) )
						.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED , 184 , Short.MAX_VALUE )
						.addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jButton2 ).addComponent( SaveButton ) ).addGap( 54 , 54 , 54 ) ) );
	}// </editor-fold>
	//GEN-END:initComponents

	private void SaveButtonMouseReleased( java.awt.event.MouseEvent evt )
	{
		settingModel.setServerIp( ServerIpTextField.getText() );
		settingModel.setServerPort( Integer.parseInt( ServerPortTextField.getText() +"" ));
		
		boolean result = readWriteSetting.setting( settingModel );
		if(result)
		{
			JOptionPane.showMessageDialog(null, "保存成功", "配置信息",JOptionPane.INFORMATION_MESSAGE);
		}
		else
		{
			JOptionPane.showMessageDialog(null, "保存失败", "配置信息",JOptionPane.ERROR_MESSAGE);
		}
	}

	

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton SaveButton;

	private javax.swing.JTextField ServerIpTextField;

	private javax.swing.JTextField ServerPortTextField;

	private javax.swing.JButton jButton2;

	private javax.swing.JLabel jLabel1;

	private javax.swing.JLabel jLabel2;
	// End of variables declaration//GEN-END:variables

}
